# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('compile', 'Compile-time error'), ('runtime', 'Runtime exception'), ('program', 'Wrong result')], max_length=32)),
                ('description', models.TextField()),
                ('read_more_link', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name='programminglanguage',
            old_name='downloadLink',
            new_name='download_link',
        ),
        migrations.AddField(
            model_name='error',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProgrammingLanguage'),
        ),
        migrations.AddField(
            model_name='error',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Problem'),
        ),
    ]
