# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161231_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='description',
            field=models.TextField(help_text='Describe what the problem is and how you can solve it'),
        ),
        migrations.AlterField(
            model_name='error',
            name='key',
            field=models.CharField(help_text='An unique-ish key that the test server reports this problem as.', max_length=64),
        ),
        migrations.AlterField(
            model_name='error',
            name='read_more_link',
            field=models.CharField(help_text='A link to read more about the error', max_length=256),
        ),
        migrations.AlterField(
            model_name='error',
            name='type',
            field=models.CharField(choices=[('compile', 'Compile-time error'), ('runtime', 'Runtime exception'), ('program', 'Wrong result')], help_text='Which step in the process the error can occur', max_length=32),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(help_text='Supports Markdown/HTML'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProblemGroup', verbose_name='Course/Problem Group'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(help_text='Name for the Problem/Lab', max_length=256),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_key',
            field=models.CharField(help_text='The name of the test on the test server that this problem will use', max_length=64, verbose_name='Test suite name'),
        ),
        migrations.AlterField(
            model_name='problemgroup',
            name='language',
            field=models.ForeignKey(help_text='The Programming Language being used for this test group', on_delete=django.db.models.deletion.CASCADE, to='app.ProgrammingLanguage'),
        ),
        migrations.AlterField(
            model_name='problemgroup',
            name='name',
            field=models.CharField(help_text='Name of course or generic problem group', max_length=64),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='docs',
            field=models.CharField(help_text='A link to the documentation for the language', max_length=256),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='download_link',
            field=models.CharField(help_text='A link to download tools for the language.', max_length=256),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='name',
            field=models.CharField(help_text='The common name for the programming language (can be including version', max_length=64),
        ),
    ]
