# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170115_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='ace_name',
            field=models.CharField(default='python', help_text='The name used in the ACE editor to provide syntax highlighting', max_length=256),
        ),
    ]
