# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_programminglanguage_ace_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('testing', 'Testing'), ('success', 'Accepted'), ('fail', 'Failed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='submission',
            name='state_data',
            field=models.TextField(blank=True),
        ),
    ]
