# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170115_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('testing', 'Testing'), ('passed', 'Accepted'), ('failed', 'Failed')], max_length=32),
        ),
    ]
