# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170116_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='state_data',
            new_name='output_log',
        ),
        migrations.AddField(
            model_name='submission',
            name='thrown_error',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Error'),
        ),
        migrations.AddField(
            model_name='submission',
            name='thrown_error_line',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='thrown_error_raw',
            field=models.TextField(blank=True),
        ),
    ]
