# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170116_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProgrammingLanguage'),
        ),
        migrations.AlterField(
            model_name='error',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Problem'),
        ),
    ]
