# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170116_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='show_output',
            field=models.BooleanField(default=True, help_text='Decides if test output should be show in a submission.'),
        ),
    ]
