# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_problem_show_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('secret_key', models.CharField(max_length=256)),
            ],
        ),
    ]
