# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170312_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='app.Problem'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='test_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='thrown_error',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Error'),
        ),
    ]
