# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-05 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20170521_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='problems', to='app.Problem'),
        ),
    ]
